# action.yaml
name: 'Lean Autoupdate Action'
description: 'A Github Action that updates to the latest lean nightly'
inputs:
  dir:
    description: 'Project Directory'
    required: true
    default: "1"
outputs:
  num_squared:
    description: 'Square of the input'
    value: ${{ steps.get-lean-version.outputs.version }}
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: pip install uv
      shell: bash
    - name: Fetch the number's square
      id: get-lean-version
      run: |
        ls
        uv run src/get_lean_version.py --dir=${{ inputs.dir }}
      shell: bash
